apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: webinar-app
  namespace: flux-system
spec:
  chart:
    spec:
      version: ">=1.0.0"
      chart: ./apps/webinar-app
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 15s
  suspend: false
  install:
    createNamespace: true
  targetNamespace: app