---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 1h0m0s
  secretRef:
    name: weave-gitops-enterprise-credentials
  url: https://charts.dev.wkp.weave.works/releases/charts-v3

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mccp
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
      version: 0.9.1
  install:
    crds: Create
  interval: 1h0m0s
  targetNamespace: flux-system
  upgrade:
    crds: CreateReplace
  values:
    config:
      capi:
        repositoryURL: https://github.com/PetrMc/webinar/clusters
      git:
        type: github

