---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-app
  labels:
    app: webinar-app
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webinar-app
      version: green
  template:
    metadata:
      labels:
        app: webinar-app
        version: green
    spec:
      containers:
      - name: webinar-app
        image: mcallisterpetr/webinar-app:green
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webinar-app
  labels:
    app: webinar-app  
    service: webinar-app
spec:
  ports:
  - port: 5000
    name: http
    targetPort: 8080
  selector:
    app: webinar-app        
---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  namespace: app
  name: tsb-gateway-app
spec: {}
