apiVersion: v1
kind: Service
metadata:
  name: webinar-app
  labels:
    app: webinar-app  
    service: webinar-app
spec:
  ports:
  - port: 5000
    name: http
    targetPort: 8080
  selector:
    app: webinar-app