apiVersion: gateway.tsb.tetrate.io/v2
kind: Tier1Gateway
metadata:
  name: app-ingress
  annotations:
    tsb.tetrate.io/organisation: partner-webinar-org
    tsb.tetrate.io/tenant: partner-webinar-tenant  
    tsb.tetrate.io/workspace: webinar-app-ws
    tsb.tetrate.io/gatewayGroup: webinar-app-gg
spec:
  workloadSelector:
    namespace: ingress
    labels:
      app: tsb-gateway-ingress
  externalServers:
  - name: webinar-app
    hostname: "webinar-app.cx.tetrate.info"      
    port: 80
    tls: {}
    clusters:
    - name: blue-v1-aws-webinar
      weight: 90
    - name: green-v2-gcp-webinar
      weight: 10
