name: Policy Check
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: [main]
    paths: [apps/webinar-ap/**]

jobs:
  check-policies:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: policy-agent-helm
      uses: weaveworks/weave-action@v1
      with:
        path: apps/webinar-app
        policies-path: policy
